### ISSUE TITLE
Closes instantly

### ISSUE THREAD

**Issue by RadNotRed** [AdotBdot/SpicetifyManagerApp#4]
When I try to open this it immediately closes

**Comment by AdotBdot** [comment]
Do you have latest release of spicetify-cli installed?

**Comment by AdotBdot** [comment]
It is known that KERNELBASE.dll throws 0xe0434352 on some computers. You can check in the Event Viewer>Windows Logs>Application if SpicetifyManagerApp throws exceptions

**Comment by AdotBdot** [comment]
Please download v1.1.0 and check if everything works fine

**Comment by RadNotRed** [comment]
Does this https://hastebin.com/xodudacodu

**Comment by AdotBdot** [comment]
When is this exception threw? After the 1.1 release app should launch properly.

**Comment by RadNotRed** [comment]
its thrown at this download, when i open it

**Comment by RadNotRed** [comment]
it also happpens when i open click the little refresh button

**Comment by AdotBdot** [comment]
> it also happpens when i open click the little refresh button

this will be repaired in closest patch
